export const monthList = [
  { nameTH: "ทั้งหมด", nameEN: "All", key: "0" },
  { nameTH: "มกราคม", nameEN: "January", key: "1" },
  { nameTH: "กุมภาพันธ์", nameEN: "February", key: "2" },
  { nameTH: "มีนาคม", nameEN: "March", key: "3" },
  { nameTH: "เมษายน", nameEN: "April", key: "4" },
  { nameTH: "พฤษภาคม", nameEN: "May", key: "5" },
  { nameTH: "มิถุนายน", nameEN: "June", key: "6" },
  { nameTH: "กรกฎาคม", nameEN: "July", key: "7" },
  { nameTH: "สิงหาคม", nameEN: "August", key: "8" },
  { nameTH: "กันยายน", nameEN: "September", key: "9" },
  { nameTH: "ตุลาคม", nameEN: "October", key: "10" },
  { nameTH: "พฤศจิกายน", nameEN: "November", key: "11" },
  { nameTH: "ธันวาคม", nameEN: "December", key: "12" },
];
